'use client'

import { motion, useInView } from 'framer-motion'
import { useRef, useState } from 'react'
import { ExternalLink, Info, MapPin, Clock, Coins } from 'lucide-react'
import { BitcoinLogoSVG } from '@/components/logos'

const CFB_ADDRESS = '1CFBdvaiZgZPTZERqnezAtDQJuGHKoHSzg'

interface AddressSegment {
  text: string
  color: string
  label: string
  description: string
}

const addressSegments: AddressSegment[] = [
  {
    text: '1',
    color: 'text-yellow-400',
    label: 'Network',
    description: 'Bitcoin mainnet prefix - indicates this is a Pay-to-Public-Key-Hash (P2PKH) address',
  },
  {
    text: 'CFB',
    color: 'text-orange-400',
    label: 'Signature',
    description: 'Come-From-Beyond - the pseudonym of Sergey Ivancheglo, Qubic and NXT creator',
  },
  {
    text: 'dva',
    color: 'text-blue-400',
    label: 'Reference',
    description: 'Possibly "dva" meaning "two" in Russian/Slavic languages - CFB\'s linguistic heritage',
  },
  {
    text: 'i',
    color: 'text-gray-400',
    label: 'Separator',
    description: 'Single character separator between meaningful segments',
  },
  {
    text: 'ZgZ',
    color: 'text-purple-400',
    label: 'Mirror',
    description: 'Palindromic pattern Z-g-Z where g is the 7th letter. Creates visual symmetry in the address',
  },
  {
    text: 'PTZ',
    color: 'text-green-400',
    label: 'Location',
    description: 'Possibly "Petrozavodsk" - the capital city of Karelia, Russia, CFB\'s reported hometown',
  },
  {
    text: 'ERqnezAtDQJuGHKoHS',
    color: 'text-muted-foreground',
    label: 'Hash Data',
    description: 'Cryptographic hash portion generated by the address derivation algorithm',
  },
  {
    text: 'zg',
    color: 'text-purple-400',
    label: 'Closing',
    description: 'Mirrors the earlier ZgZ pattern - bookend symmetry in the address structure',
  },
]

interface SegmentTooltipProps {
  segment: AddressSegment
  isActive: boolean
  onHover: (active: boolean) => void
}

function SegmentDisplay({ segment, isActive, onHover }: SegmentTooltipProps) {
  return (
    <div className="relative inline-block">
      <motion.span
        className={`font-mono text-lg sm:text-xl cursor-pointer ${segment.color} ${
          isActive ? 'bg-white/10 rounded px-1' : ''
        }`}
        onMouseEnter={() => onHover(true)}
        onMouseLeave={() => onHover(false)}
        whileHover={{ scale: 1.05 }}
      >
        {segment.text}
      </motion.span>
    </div>
  )
}

export function CFBAddressBreakdown() {
  const sectionRef = useRef(null)
  const isInView = useInView(sectionRef, { once: true, margin: '-100px' })
  const [activeSegment, setActiveSegment] = useState<number | null>(null)

  return (
    <section ref={sectionRef} className="py-20 px-4 bg-gradient-to-b from-orange-950/10 to-transparent">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <motion.div
          className="text-center mb-10"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.6 }}
        >
          <div className="flex items-center justify-center gap-3 mb-4">
            <BitcoinLogoSVG size={32} />
            <h2 className="text-2xl md:text-3xl font-semibold">
              The 1CFB Bitcoin Address
            </h2>
          </div>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            A Bitcoin address from January 2009 that appears to encode the identity
            of its creator through carefully structured character patterns.
          </p>
        </motion.div>

        {/* Main Address Display */}
        <motion.div
          className="p-6 rounded-xl bg-gradient-to-b from-orange-950/30 to-orange-950/10 border border-orange-900/50 mb-6"
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          {/* Address with segmented highlighting */}
          <div className="flex flex-wrap justify-center items-center gap-0 p-4 bg-black/30 rounded-lg mb-4">
            {addressSegments.map((segment, index) => (
              <SegmentDisplay
                key={index}
                segment={segment}
                isActive={activeSegment === index}
                onHover={(active) => setActiveSegment(active ? index : null)}
              />
            ))}
          </div>

          {/* Active Segment Info */}
          <div className="min-h-[80px] p-4 bg-black/20 rounded-lg">
            {activeSegment !== null && addressSegments[activeSegment] ? (
              <motion.div
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.2 }}
              >
                <div className="flex items-center gap-2 mb-2">
                  <span className={`font-mono font-bold ${addressSegments[activeSegment].color}`}>
                    {addressSegments[activeSegment].text}
                  </span>
                  <span className="text-xs px-2 py-0.5 rounded bg-white/10">
                    {addressSegments[activeSegment].label}
                  </span>
                </div>
                <p className="text-sm text-muted-foreground">
                  {addressSegments[activeSegment].description}
                </p>
              </motion.div>
            ) : (
              <div className="text-center text-sm text-muted-foreground">
                <Info className="h-4 w-4 inline-block mr-2" />
                Hover over address segments to see their meaning
              </div>
            )}
          </div>
        </motion.div>

        {/* Metadata Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
          <motion.div
            className="p-4 rounded-xl bg-card/50 border border-border"
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ delay: 0.2 }}
          >
            <div className="flex items-center gap-2 mb-2">
              <Clock className="h-4 w-4 text-orange-400" />
              <span className="text-sm font-medium">First Seen</span>
            </div>
            <div className="font-mono text-lg">Jan 13, 2009</div>
            <div className="text-xs text-muted-foreground">Block #521</div>
          </motion.div>

          <motion.div
            className="p-4 rounded-xl bg-card/50 border border-border"
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ delay: 0.25 }}
          >
            <div className="flex items-center gap-2 mb-2">
              <Coins className="h-4 w-4 text-orange-400" />
              <span className="text-sm font-medium">Balance Received</span>
            </div>
            <div className="font-mono text-lg">50 BTC</div>
            <div className="text-xs text-muted-foreground">Original block reward</div>
          </motion.div>

          <motion.div
            className="p-4 rounded-xl bg-card/50 border border-border"
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ delay: 0.3 }}
          >
            <div className="flex items-center gap-2 mb-2">
              <MapPin className="h-4 w-4 text-orange-400" />
              <span className="text-sm font-medium">Status</span>
            </div>
            <div className="font-mono text-lg text-green-400">Dormant</div>
            <div className="text-xs text-muted-foreground">Never moved since 2009</div>
          </motion.div>

          <motion.div
            className="p-4 rounded-xl bg-card/50 border border-border"
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ delay: 0.35 }}
          >
            <div className="flex items-center gap-2 mb-2">
              <Info className="h-4 w-4 text-orange-400" />
              <span className="text-sm font-medium">1CFB Addresses</span>
            </div>
            <div className="font-mono text-lg">12 unique</div>
            <div className="text-xs text-muted-foreground">All from 2009-2010</div>
          </motion.div>
        </div>

        {/* Pattern Analysis */}
        <motion.div
          className="p-5 rounded-xl bg-gradient-to-r from-orange-950/30 via-purple-950/30 to-orange-950/30 border border-orange-900/50"
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
          transition={{ duration: 0.5, delay: 0.4 }}
        >
          <h3 className="font-semibold mb-4">Pattern Analysis</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-3 rounded bg-black/20">
              <div className="text-sm text-muted-foreground mb-1">Mirror Symmetry</div>
              <div className="font-mono">
                <span className="text-purple-400">ZgZ</span>
                <span className="text-muted-foreground"> ... </span>
                <span className="text-purple-400">zg</span>
              </div>
              <div className="text-xs text-muted-foreground mt-1">
                Palindromic bookends
              </div>
            </div>
            <div className="p-3 rounded bg-black/20">
              <div className="text-sm text-muted-foreground mb-1">Letter Position</div>
              <div className="font-mono">
                <span className="text-blue-400">g</span>
                <span className="text-muted-foreground"> = </span>
                <span className="text-white">7th letter</span>
              </div>
              <div className="text-xs text-muted-foreground mt-1">
                7 appears in Qubic architecture
              </div>
            </div>
            <div className="p-3 rounded bg-black/20">
              <div className="text-sm text-muted-foreground mb-1">CFB Signature</div>
              <div className="font-mono">
                <span className="text-yellow-400">1</span>
                <span className="text-orange-400">CFB</span>
                <span className="text-muted-foreground">...</span>
              </div>
              <div className="text-xs text-muted-foreground mt-1">
                Come-From-Beyond identity
              </div>
            </div>
          </div>
        </motion.div>

        {/* External Link */}
        <motion.div
          className="mt-6 text-center"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : { opacity: 0 }}
          transition={{ delay: 0.5 }}
        >
          <a
            href={`https://blockchair.com/bitcoin/address/${CFB_ADDRESS}`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-orange-500/20 hover:bg-orange-500/30 transition-colors text-orange-400"
          >
            <ExternalLink className="h-4 w-4" />
            View on Blockchair
          </a>
        </motion.div>

        {/* Research Integrity Notice */}
        <motion.div
          className="mt-6 p-4 rounded-lg bg-card/50 border border-border text-center"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : { opacity: 0 }}
          transition={{ delay: 0.6 }}
        >
          <p className="text-xs text-muted-foreground">
            <strong>Verification:</strong> This address and its transaction history can be verified
            on any Bitcoin blockchain explorer. First transaction: Block #521, January 13, 2009.
          </p>
        </motion.div>
      </div>
    </section>
  )
}
