'use client'

import { useRef, useState, useEffect } from 'react'
import { motion, useInView, AnimatePresence } from 'framer-motion'
import { JourneySection } from '../JourneySection'
import { ExternalLink, Info, Clock, Coins, MapPin, AlertCircle, Fingerprint } from 'lucide-react'
import { BitcoinLogoSVG } from '@/components/logos'

const CFB_ADDRESS = '1CFBdvaiZgZPTZERqnezAtDQJuGHKoHSzg'

interface AddressSegment {
  text: string
  color: string
  label: string
  description: string
}

const addressSegments: AddressSegment[] = [
  {
    text: '1',
    color: 'text-[#D4AF37]',
    label: 'Network',
    description: 'This "1" means it\'s a real Bitcoin address on the main network (not a test)',
  },
  {
    text: 'CFB',
    color: 'text-[#D4AF37]',
    label: 'Signature',
    description: '"CFB" stands for "Come-From-Beyond" - a famous cryptographer who created multiple blockchain projects',
  },
  {
    text: 'dva',
    color: 'text-[#D4AF37]',
    label: 'Language',
    description: '"dva" means "two" in Russian - a hint about the creator\'s Eastern European origins',
  },
  {
    text: 'i',
    color: 'text-white/40',
    label: 'Separator',
    description: 'A simple separator between the meaningful parts of this address',
  },
  {
    text: 'ZgZ',
    color: 'text-[#D4AF37]',
    label: 'Mirror Pattern',
    description: 'This is a palindrome (reads same forwards and backwards) - intentional symmetry',
  },
  {
    text: 'PTZ',
    color: 'text-[#D4AF37]',
    label: 'Location Hint',
    description: 'Possibly "Petrozavodsk" - a city in Russia. Could reveal the creator\'s hometown',
  },
  {
    text: 'ERqnezAtDQJuGHKoHS',
    color: 'text-white/50',
    label: 'Random Data',
    description: 'This cryptographic portion is generated by Bitcoin\'s algorithm - not chosen by the creator',
  },
  {
    text: 'zg',
    color: 'text-[#D4AF37]',
    label: 'Closing Mirror',
    description: 'Mirrors the earlier "ZgZ" pattern - deliberate bookend symmetry in the address',
  },
]

export function GenesisSection() {
  const contentRef = useRef(null)
  const isInView = useInView(contentRef, { once: false, amount: 0.2 })
  const [activeSegment, setActiveSegment] = useState<number | null>(null)
  const [showAddress, setShowAddress] = useState(false)

  // Show address after story intro
  useEffect(() => {
    if (isInView) {
      const timer = setTimeout(() => setShowAddress(true), 1500)
      return () => clearTimeout(timer)
    } else {
      setShowAddress(false)
    }
  }, [isInView])

  return (
    <JourneySection id="genesis" background="transparent" className="flex items-center justify-center py-12 md:py-20">
      <div ref={contentRef} className="relative z-10 w-full max-w-5xl mx-auto px-4">
        {/* Story Intro - Setting the Scene */}
        <motion.div
          className="text-center mb-12"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 20 }}
          transition={{ duration: 0.8 }}
        >
          {/* Chapter indicator */}
          <motion.div
            className="inline-flex items-center gap-2 mb-6"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: isInView ? 1 : 0, scale: isInView ? 1 : 0.9 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <span className="px-3 py-1 rounded-full bg-white/5 border border-white/10 text-white/50 text-xs font-mono">
              CHAPTER 1
            </span>
          </motion.div>

          <motion.div
            className="flex items-center justify-center gap-3 mb-4"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: isInView ? 1 : 0, scale: isInView ? 1 : 0.9 }}
            transition={{ duration: 0.6, delay: 0.3 }}
          >
            <BitcoinLogoSVG size={48} />
          </motion.div>

          <h2 className="text-3xl md:text-5xl font-bold text-white/90 mb-6">
            The First Clue
          </h2>

          {/* Story paragraph for beginners */}
          <motion.div
            className="max-w-2xl mx-auto space-y-4 mb-8"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 10 }}
            transition={{ duration: 0.8, delay: 0.5 }}
          >
            <p className="text-lg text-white/50 leading-relaxed">
              Just <span className="text-white/70 font-medium">10 days</span> after Bitcoin was created,
              something unusual appeared on the blockchain.
            </p>
            <p className="text-base text-white/40 leading-relaxed">
              A Bitcoin address isn't just random letters and numbers.
              If you're clever enough, you can <span className="text-white/60">embed hidden messages</span> within it.
            </p>
          </motion.div>

          {/* Date highlight */}
          <motion.div
            className="inline-flex items-center gap-3 px-4 py-2 bg-white/5 border border-white/10"
            initial={{ opacity: 0 }}
            animate={{ opacity: isInView ? 1 : 0 }}
            transition={{ delay: 0.7 }}
          >
            <Clock className="h-4 w-4 text-white/50" />
            <span className="text-white/60 font-mono">January 13, 2009</span>
            <span className="text-white/50">•</span>
            <span className="text-white/40 text-sm">Block #521</span>
          </motion.div>
        </motion.div>

        {/* The Address - Main reveal */}
        <motion.div
          className="p-6 md:p-8 rounded-2xl bg-gradient-to-b from-[#050505] to-black/50 border border-orange-900/30 mb-8 relative overflow-hidden"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 30 }}
          transition={{ duration: 0.6, delay: 0.8 }}
        >
          {/* Fingerprint watermark */}
          <div className="absolute top-4 right-4 opacity-10">
            <Fingerprint className="w-16 h-16 text-[#D4AF37]" />
          </div>

          {/* Label */}
          <div className="flex items-center gap-2 mb-4">
            <AlertCircle className="h-4 w-4 text-[#D4AF37]" />
            <span className="text-sm text-[#D4AF37]/80 font-medium">The 1CFB Bitcoin Address</span>
          </div>

          {/* Address with segmented highlighting */}
          <div className="flex flex-wrap justify-center items-center gap-0 p-4 md:p-6 bg-black/40 mb-4">
            {addressSegments.map((segment, index) => (
              <motion.span
                key={index}
                className={`font-mono text-base sm:text-xl md:text-2xl cursor-pointer transition-all duration-200 ${segment.color} ${
                  activeSegment === index ? 'bg-white/10  px-1 scale-110' : 'hover:bg-white/5'
                }`}
                onMouseEnter={() => setActiveSegment(index)}
                onMouseLeave={() => setActiveSegment(null)}
                onClick={() => setActiveSegment(activeSegment === index ? null : index)}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 10 }}
                transition={{ duration: 0.3, delay: 1 + index * 0.05 }}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                {segment.text}
              </motion.span>
            ))}
          </div>

          {/* Active Segment Info */}
          <div className="min-h-[100px] p-4 bg-black/30">
            <AnimatePresence mode="wait">
              {activeSegment !== null && addressSegments[activeSegment] ? (
                <motion.div
                  key={activeSegment}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.2 }}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span className={`font-mono text-xl font-bold ${addressSegments[activeSegment].color}`}>
                      {addressSegments[activeSegment].text}
                    </span>
                    <span className="text-xs px-2 py-1 rounded-full bg-white/10 text-white/60">
                      {addressSegments[activeSegment].label}
                    </span>
                  </div>
                  <p className="text-sm text-white/60 leading-relaxed">
                    {addressSegments[activeSegment].description}
                  </p>
                </motion.div>
              ) : (
                <motion.div
                  key="default"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="text-center"
                >
                  <div className="text-sm text-white/50 mb-2">
                    <Info className="h-4 w-4 inline-block mr-2" />
                    Tap or hover on each colored segment to decode its meaning
                  </div>
                  <p className="text-xs text-white/20">
                    This address was deliberately crafted to contain hidden information
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </motion.div>

        {/* Key Facts - Simplified for beginners */}
        <motion.div
          className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4 mb-8"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 20 }}
          transition={{ duration: 0.6, delay: 1.2 }}
        >
          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <Clock className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-white/80">2009</div>
            <div className="text-xs text-white/40">Created</div>
          </div>

          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <Coins className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-white/80">50 BTC</div>
            <div className="text-xs text-white/40">Received</div>
          </div>

          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <MapPin className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-[#D4AF37]">Untouched</div>
            <div className="text-xs text-white/40">17 years</div>
          </div>

          <div className="p-4 bg-white/5 border border-white/10 text-center">
            <Fingerprint className="h-5 w-5 text-[#D4AF37] mx-auto mb-2" />
            <div className="font-mono text-lg text-white/80">12</div>
            <div className="text-xs text-white/40">1CFB addresses</div>
          </div>
        </motion.div>

        {/* The Question */}
        <motion.div
          className="p-6 bg-gradient-to-r from-[#050505]/80 via-purple-950/20 to-[#050505]/80 border border-white/10 text-center mb-8"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 30 }}
          transition={{ duration: 0.5, delay: 1.4 }}
        >
          <p className="text-lg text-white/60 mb-2">The Question:</p>
          <p className="text-xl md:text-2xl text-white/80 font-medium">
            Who is <span className="text-[#D4AF37]">CFB</span>?
          </p>
          <p className="text-sm text-white/40 mt-3">
            And why would someone embed their identity in Bitcoin's earliest blocks?
          </p>
        </motion.div>

        {/* External Link */}
        <motion.div
          className="text-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: isInView ? 1 : 0 }}
          transition={{ delay: 1.6 }}
        >
          <a
            href={`https://blockchair.com/bitcoin/address/${CFB_ADDRESS}`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#D4AF37]/10 hover:bg-[#D4AF37]/20 transition-all text-[#D4AF37]/80 text-sm border border-orange-500/20"
          >
            <ExternalLink className="h-4 w-4" />
            Verify this address on the blockchain
          </a>
          <p className="text-xs text-white/50 mt-2">
            Anyone can verify this - the blockchain is public
          </p>
        </motion.div>
      </div>
    </JourneySection>
  )
}
